### ISSUE TITLE
[FEATURE REQUEST] Allow specifying a Postgres database for each validator/actor

### ISSUE THREAD

**Issue by okdas** [pokt-network/pocket-operator#3]
As an operator user, I want to be able to specify a postgres database via an argument for CRD object, to provision the database outside the pocket-operator lifecycle (such as RDS).

We should make use of `secretKeyRef`/`SecretKeySelector` type - https://github.com/kubernetes/api/blob/669318b25bc70fee14165aa37ffb3f354e58a71f/core/v1/types.go#L2064 to enforce utilizing secret objects.

**Comment by Olshansk** [comment]
Could this noe be done via the configs in the core repo directly?

**Comment by Olshansk** [comment]
@okdas CLosing this out as done!
