### ISSUE TITLE
[FEATURE REQUEST] Utilize kubernetes secrets for private keys

### ISSUE THREAD

**Issue by okdas** [pokt-network/pocket-operator#4]
As an operator user, I want to utilize Kubernetes secrets to store private keys, so my super secret data kept secret and neven showed in the object spec/status.

We should utilize `SecretKeySelector` for this (unless there's a better alternative?).

**Comment by Olshansk** [comment]
@okdas Is there more you wanted to do here relative to what we have? I know we're not utilizing `SecretKeySelector`, but we have. keybase now.

**Comment by okdas** [comment]
@Olshansk I don't think we need to do anything else for keys management with Kubernetes.
